# Generated by Django 2.0.3 on 2018-11-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1),
        ),
        migrations.RemoveField(
            model_name='platter',
            name='size',
        ),
        migrations.AddField(
            model_name='platter',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1),
        ),
        migrations.RemoveField(
            model_name='sub',
            name='size',
        ),
        migrations.AddField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
