# Generated by Django 2.0.3 on 2018-11-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='name',
            field=models.CharField(choices=[('M', 'Mushrooms'), ('G', 'Green Peppers'), ('O', 'Onions')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='name',
            field=models.CharField(choices=[('BZMO', 'Baked Ziti with Mozzarella'), ('BZME', 'Baked Ziti with Meatballs'), ('BZCH', 'Baked Ziti with Chicken')], max_length=4),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0),
        ),
        migrations.AlterField(
            model_name='platter',
            name='name',
            field=models.CharField(choices=[('GAR', 'Garden Salad'), ('GRE', 'Greek Salad'), ('ANT', 'Antipasto'), ('BAK', 'Baked Ziti'), ('MEA', 'Meatball Parm'), ('CHI', 'Chicken Parm')], max_length=3),
        ),
        migrations.AlterField(
            model_name='salad',
            name='name',
            field=models.CharField(choices=[('GAR', 'Garden Salad'), ('GRE', 'Greek Salad'), ('ANT', 'Antipasto'), ('SWT', 'Salad with Tuna')], max_length=3),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(choices=[('PEP', 'Pepperoni'), ('SAU', 'Sausages'), ('MUS', 'Mushrooms'), ('ONI', 'Onions'), ('HAM', 'Ham'), ('CAN', 'Canadian Bacon'), ('PIN', 'Pineapple'), ('EGG', 'Eggplant'), ('TAB', 'Tomato and Basil'), ('GRE', 'Green Peppers'), ('BUR', 'Hamburger'), ('SPI', 'Spinach'), ('ART', 'Artichoke'), ('BUF', 'Buffalo Chicken'), ('BAR', 'Barbecue Chicken'), ('ANC', 'Anchovies'), ('BLA', 'Black Olives'), ('FRE', 'Fresh Garlic'), ('ZUC', 'Zucchini')], max_length=3),
        ),
    ]
