# Generated by Django 2.0.3 on 2018-11-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20181115_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='name',
            field=models.CharField(choices=[('CHE', 'Cheese'), ('ITA', 'Italian'), ('HPC', 'Ham plus Cheese'), ('MEA', 'Meatball'), ('TUN', 'Tuna'), ('TUR', 'Turkey'), ('CHP', 'Chicken Parmigiana'), ('EGP', 'Eggplant Parmigiana'), ('STE', 'Steak'), ('SPC', 'Steak plus Cheese'), ('SPO', 'Sausage, Peppers and Onions'), ('HAM', 'Hamburger'), ('CHB', 'Cheeseburger'), ('FRC', 'Fried Chicken'), ('VEG', 'Veggie')], max_length=3),
        ),
    ]
