# Generated by Django 2.0.3 on 2018-11-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181115_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salad',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
