# Generated by Django 2.0.3 on 2018-12-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20181127_2320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extra',
        ),
    ]
